runtime: python37
env: standard
service: default
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app #これを描かないときはサーバーエラーなったけどうまくいった # -> この状態でうまくいった

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
